# H.W #1
* Due Date : 2023-09-29 / 23:55
* eclass에서만 과제 제출 가능 (이메일을 통한 제출은 받지 않음)
* 하나의 .ipynb 파일로 제출
* 마감 기한 엄수

##  #1

* 한 고등학교 학생의 과목별 기말고사 점수는 다음과 같다.

과목 | 점수
:-- | :--
국어 | 90 |
영어 | 75
수학 | 70
물리 | 40
지구과학 | 36
한국사 | 70

* if-elif-else문을 이용하여 수학(변수명 : math) 점수 등급을 부여하라.
    * 80점 이상이면 "1등급" 출력
    * 68점 이상 80점 미만이면 "2등급" 출력
    * 55점 이상 68점 미만이면 "3등급" 출력
    * 43점 이상 55점 미만이면 "4등급" 출력
    * 43점 미만이면 "5등급 이하" 출력

In [ ]:
math = 70

if math >= 80:
    print("1등급")
elif math<80 and math>=68:
    print("2등급")
elif math<68 and math>=70:
    print("3등급")
elif math<55 and math>=43:
    print("4등급")
else:
    print("5등급 이하")

2등급


* 이 학생의 국영수 평균 점수를 avg() 함수를 생성하여 구하라.
    * 매개변수 개수를 지정할 수 없는 경우의 함수 생성
    * 평균 점수는 소수점 뒤를 반올림한 값 반환할 것

In [ ]:
def avg(*n):
  result=0
  for i in n:
      result += i
  return round(result/len(n))

In [ ]:
avg(90,75,70)

78

# #2

* while 문을 사용하여 1부터 100까지의 자연수 중 5의 배수의 합을 구하라.
    * 5의 배수는 5로 나누어 떨어지는 수이다
    * "총합은 1050입니다" 가 출력되도록 할 것

In [ ]:
result = 0
i=1
while i <= 100:
    if i % 5 == 0:
        result += i
    i += 1

print("총합은 %d 입니다" % result)

총합은 1050 입니다


* for문과 range함수를 사용하여 1부터 100까지의 합을 구하라

In [2]:
result = 0
for j in range(1,101):
    result += j

print(result)

5050


# #3

* 한 통계학과 학생의 주민등록번호는 021120-1068234 이다.
* 이 학생의 주민등록번호를 연월일(YYYYMMDD) 부분과 성별을 나타내는 숫자를 출력하라.
* 변수명 : pin

In [ ]:
pin = "021120-1068234"

yyyymmdd = pin[:6]
num = pin[7]

print(yyyymmdd)
print(num)

021120
1


# #4

* for와 range 함수를 사용하여 file.txt 파일에 구구단을 저장하라.
* 구구단은 2단부터 9단까지 줄바꿈을 이용해 출력될 수 있도록 할 것.
* 마지막에는 !cat 함수를 이용하여 내용 출력할 것.

In [ ]:
with open("file.txt","w") as f:
  for i in range(2, 10):
    for j in range(1,10):
      f.write("{0}x{1}={2}\n".format(i, j, i*j))

!cat file.txt

2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
3x1=3
3x2=6
3x3=9
3x4=12
3x5=15
3x6=18
3x7=21
3x8=24
3x9=27
4x1=4
4x2=8
4x3=12
4x4=16
4x5=20
4x6=24
4x7=28
4x8=32
4x9=36
5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
6x1=6
6x2=12
6x3=18
6x4=24
6x5=30
6x6=36
6x7=42
6x8=48
6x9=54
7x1=7
7x2=14
7x3=21
7x4=28
7x5=35
7x6=42
7x7=49
7x8=56
7x9=63
8x1=8
8x2=16
8x3=24
8x4=32
8x5=40
8x6=48
8x7=56
8x8=64
8x9=72
9x1=9
9x2=18
9x3=27
9x4=36
9x5=45
9x6=54
9x7=63
9x8=72
9x9=81


# #5

* 평균이 7, 분산이 10인 정규분포시행에서 성공할 횟수에 대해 랜덤하게 추출된 표본으로 (2,3) 배열 생성하라.

In [7]:
import numpy as np
np.random.seed(202)
a = np.random.normal(7, 10, size=(2,3))
print(a)

[[-0.35873742 -1.60153161 -2.23282409]
 [ 9.38453125  1.16783748 13.74325528]]


* 0행의 0열값과 1행의 1열값을 출력하라.

In [ ]:
row = [0, 1]
col = [0, 1]

print(a[row, col])

[-6.65873742 -5.13216252]


* 모든 행과 열을 거꾸로 출력하라.

In [ ]:
print(a[::-1, ::-1])

[[ 7.44325528 -5.13216252  3.08453125]
 [-8.53282409 -7.90153161 -6.65873742]]


* 10 이상의 원소들만 출력하라.

In [8]:
b = a>10
print(b)

print(a[b])

[[False False False]
 [False False  True]]
[13.74325528]
